FROM swift:5.8.0-focal AS builder

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && apt-get -q update && \
    apt-get install -y \
    libjavascriptcoregtk-4.0-dev \
    unzip

WORKDIR /root/Pamphlet
COPY ./dist ./dist
COPY ./.build/repositories ./.build/repositories
COPY ./.git ./.git
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

# RUN swift test
RUN swift build --configuration release

FROM swift:5.7.1-focal

WORKDIR /root/Pamphlet
COPY --from=builder /root/Pamphlet/.build/release/PamphletTool .
COPY --from=builder /root/Pamphlet/.build/release/PamphletTool .
