FROM fedora:37 as builder

RUN dnf install -y \
    git \
    unzip \
    swift-lang-5.7-1.fc37 \
    javascriptcoregtk4.0-devel \
    libatomic_ops

WORKDIR /root/Pamphlet
COPY ./dist ./dist
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift test
RUN swift build --configuration release

FROM fedora:37

WORKDIR /root/Pamphlet
COPY --from=builder /root/Pamphlet/.build/release/PamphletTool-focal .
COPY --from=builder /root/Pamphlet/.build/release/PamphletTool-focal .
