FROM swift:5.7.1-amazonlinux2 as builder

RUN yum install -y \
    libatomic \
    webkitgtk4-jsc-devel \
    unzip

WORKDIR /root/Pamphlet
COPY ./dist ./dist
COPY ./Package.resolved ./Package.resolved
COPY ./Package.swift ./Package.swift
COPY ./Plugins ./Plugins
COPY ./Sources ./Sources
COPY ./Tests ./Tests

RUN swift test
RUN swift build --configuration release

FROM fedora:37

WORKDIR /root/Pamphlet
COPY --from=builder /root/Pamphlet/.build/release/PamphletTool-focal .
COPY --from=builder /root/Pamphlet/.build/release/PamphletTool-focal .
